version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: CsvTextFieldParser\CsvTextFieldParser.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: CsvTextFieldParser\bin\Release\*.nupkg
- path: CsvTextFieldParser\bin\Release\netstandard2.0\*.*
